### ISSUE TITLE
jsのテスト導入

### ISSUE THREAD

**Issue by kasai441** [kasai441/ruumarker#86]
- [Jest + TypeScript + Vue 3環境で Vue Testing Library(@testing-library／vue) を動かす | フューチャー技術ブログ](https://future-architect.github.io/articles/20210614b/)

- [Jest を使用した単一ファイルコンポーネントのテスト \| Vue Test Utils](https://v1.test-utils.vuejs.org/ja/installation/testing-single-file-components-with-jest.html)

> 注意: vue-jest は現在、カスタムブロックのサポートやスタイルのロードなど、vue-loader のすべての機能をサポートしていません。さらに、コード分割などの Webpack 固有の機能はサポートされていません。サポートされていない機能を使用するには、 Jest の代わりに Mocha をテストランナーとして使用します。そして、 Webpack をコンポーネントをコンパイルするために使用します。

- [Mocha \+ webpack による単一ファイルコンポーネントのテスト \| Vue Test Utils](https://v1.test-utils.vuejs.org/ja/installation/testing-single-file-components-with-mocha-webpack.html)

- [mocha による自動テスト](https://ja.javascript.info/testing-mocha)

**Comment by kasai441** [comment]
Mochaの導入

```shell
yarn add --dev @vue/test-utils mocha mocha-webpack jsdom jsdom-global
```

**Comment by kasai441** [comment]
開発環境はうまく動いたが、プロダクション環境でCan't resolve 'regenerator-runtime/runtimeがでてしまうので、

- [jsのビルドで「Can't resolve 'regenerator-runtime/runtime'」が出た時の対策 - Qiita](https://qiita.com/riversun/items/92e140f6f7a759b07047)

これに従ってregenerator-runtimeを追加したらうごいた。

ちなみにcore-jsについて軽く調べた

- [core-jsがメンテされていない理由→プロジェクトは継続する - Qiita](https://qiita.com/yumetodo/items/eaf3b97aeae3d8c4a07e)

**Comment by kasai441** [comment]
[Mocha用のテストファイルでESLintエラー'describe' is not defined no\-undef \- Qiita](https://qiita.com/yuta0801/items/3f1d57593130b50bbf88)

**Comment by kasai441** [comment]
実行すると

TypeError: compiler.plugin is not a function

というエラー

しらべたら、mocha-webpackがめちゃめちゃ古い！

https://github.com/zinserjan/mocha-webpack

mochaは再検討

**Comment by kasai441** [comment]
[Getting Started \| Vue Test Utils](https://test-utils.vuejs.org/guide/)
こっちを参考にすべき

**Comment by kasai441** [comment]
```shell
yarn add --dev @vue/test-utils babel-jest jest vue-jest
```

**Comment by kasai441** [comment]
https://github.com/vuejs/vue-jest

```shell
yarn add babel-core@bridge --dev
```

**Comment by kasai441** [comment]
テストを走らせると以下のようにimportが読み込めないのでBabelがうまく設定できてないっぽい

```shell
$ yarn test
yarn run v1.22.17
$ jest specjs/*.{js,vue}
 FAIL  specjs/demo.spec.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/kasai441/environment/ruumarker/specjs/demo.spec.js:3
    import { mount } from '@vue/test-utils'
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.369 s
Ran all test suites matching /specjs\/demo.spec.js|specjs\/*.vue/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

https://qiita.com/daiki7nohe/items/8d29e2d9059296b75fa6

この記事にあるように`.babelrc`に
```shell
{
  "presets": [
    ["env", { "modules": false }]
  ],
  "env": {
    "test": {
      "presets": [
        ["env", { "targets": { "node": "current" }}]
      ]
    }
  }
}
```

と書くと、
```shell
● Validation Error:

  Module babel-jest should have "jest-preset.js" or "jest-preset.json" file at the root.
```
こういうエラーになるので、

```shell
{
  "presets": [
    "@babel/preset-env"
  ]
}
```

やぶれかぶれでもう一度テストを実行するとエラーの内容が変わった

```shell
$ yarn test
yarn run v1.22.17
$ jest specjs/*.{js,vue}
 FAIL  specjs/demo.spec.js
  ✕ renders a todo (1 ms)

  ● renders a todo

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: document is not defined

       5 |
       6 | test('renders a todo', () => {
    >  7 |   const wrapper = mount(Mark)
         |                   ^
       8 |
       9 |   const todo = wrapper.get('[data-test="todo"]')
      10 |

      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7757:14)
      at Object.<anonymous> (specjs/demo.spec.js:7:19)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.596 s
Ran all test suites matching /specjs\/demo.spec.js|specjs\/*.vue/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kasai441** [comment]
上記のエラーは

https://shinshin86.hateblo.jp/entry/2021/10/23/120831

これで解決
